jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: ivy-${{ hashFiles('**/ivy.xml') }}
        path: 'ivyCache

          lib

          '
        restore-keys: 'ivy-

          '
    - continue-on-error: true
      name: Build with Ant
      run: ant -noinput dist
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: lombok.jar
        path: dist/lombok.jar
  docker-integration-test:
    env:
      IMAGE_NAME: lombok-${{ matrix.tool.name }}-jdk${{ matrix.jdk }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: lombok.jar
    - continue-on-error: true
      name: Build container
      run: docker build --build-arg jdk=${{ matrix.jdk }} -t $IMAGE_NAME -f ${{ matrix.tool.name
        }}/Dockerfile .
      working-directory: ./docker
    - continue-on-error: true
      name: Compile in container
      run: docker run --entrypoint="" -v $(pwd)/lombok.jar:/workspace/lombok.jar $IMAGE_NAME
        /bin/bash -c "cd classpath; ${{ matrix.tool.cmd }}"
    strategy:
      fail-fast: false
      matrix:
        exclude:
        - jdk: 22
          tool:
            cmd: gradle assemble
            name: gradle
        jdk:
        - 8
        - 11
        - 17
        - 21
        - 22
        tool:
        - cmd: mvn compile
          name: maven
        - cmd: gradle assemble
          name: gradle
        - cmd: ant dist
          name: ant
        - cmd: bazel build //:ProjectRunner
          name: bazel
  test-eclipse:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: ivy-${{ hashFiles('**/ivy.xml') }}
        path: 'ivyCache

          lib

          '
        restore-keys: 'ivy-

          '
    - continue-on-error: true
      if: ${{ !endsWith(matrix.version, 'full') }}
      name: Cache base testenv
      uses: actions/cache@v4
      with:
        key: base-testenv-${{ hashFiles('**/setup.ant.xml') }}
        path: 'testenv

          '
    - continue-on-error: true
      if: ${{ endsWith(matrix.version, 'full') }}
      name: Cache full testenv
      uses: actions/cache@v4
      with:
        key: ${{ matrix.version }}-testenv-${{ hashFiles('**/setup.ant.xml') }}
        path: 'testenv

          '
    - continue-on-error: true
      name: Build with Ant
      run: xvfb-run ant -noinput dist test.${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
        - eclipse-oxygen
        - eclipse-202006
        - eclipse-202006-jdk8
        - eclipse-202212
        - eclipse-202309
        - eclipse-202312
        - eclipse-202403
        - eclipse-I-build
        - eclipse-oxygen-full
        - eclipse-2022-03-full
        - eclipse-2023-09-full
        - eclipse-2023-12-full
        - eclipse-2024-03-full
        - eclipse-I-build-full
        - ecj11
        - ecj14
        - ecj16
        - ecj19
  test-javac:
    env:
      EA_JDK: 22
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ matrix.jdk < env.EA_JDK }}
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      if: ${{ matrix.jdk >= env.EA_JDK }}
      name: Set up JDK ${{ matrix.jdk }} Early Access release
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.jdk }}
        version: latest
        website: jdk.java.net
    - continue-on-error: true
      env:
        ANT_VERSION: 1.10.14
      name: Install Ant
      run: 'wget https://archive.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.zip

        unzip apache-ant-$ANT_VERSION-bin.zip -d "${HOME}"

        echo "ANT_HOME=${HOME}/apache-ant-$ANT_VERSION" >> $GITHUB_ENV

        echo "${HOME}/apache-ant-$ANT_VERSION/bin" >> $GITHUB_PATH

        '
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: ivy-${{ hashFiles('**/ivy.xml') }}
        path: 'ivyCache

          lib

          '
        restore-keys: 'ivy-

          '
    - continue-on-error: true
      name: Run tests
      run: ant -noinput test.${{ matrix.goal }}
    strategy:
      fail-fast: false
      matrix:
        goal:
        - javacCurrent
        include:
        - goal: javac6
          jdk: 11
        - goal: javac8
          jdk: 11
        jdk:
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
name: Tests
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
